# Site settings
title: Should I Build a Grid System?
description: There are so many grid systems out there, and grid frameworks that are even more powerful. There is no reason to create or roll your own.
baseurl: ""
url: "http://shouldibuildagridsystem.com"

exclude:
  - README.md
  - config.rb
  - package.json
  - gulpfile.js
  - node_modules
  - Gemfile
  - Gemfile.lock
  - css

# Build settings
markdown: kramdown

assets:
  dirname: assets
  sources:
    - css
  css_compressor: 'yui'
  cache: true
